// Seed content for the Rulebook Oracle demo game: "Steeldusk".
// A compact, 100% homebrew d6 fantasy ruleset we own outright.
//
// The content is engineered so the Knowledge Base demonstrably resolves
// conflicts between the core rulebook and later errata/FAQs:
//   - 4 errata entries have changeType 'override'  (they contradict the core book)
//   - 6 errata entries have changeType 'clarify'   (they confirm/reword the core book)
//   - 10 FAQs reference sections and reflect the current (post-errata) ruling.
//
// 'sourceUrl' values point at a fictional official rules site — swap them for a
// real URL if you host your own rulebook.

export const ruleSections = [
  {
    slug: 'what-you-need',
    title: 'What You Need',
    chapter: 'Foundations',
    tags: ['core'],
    body: 'Steeldusk needs only a handful of six-sided dice (d6), a pencil, and the kitchen table. Each player creates a hero with the rules in Chapter 2. The Game Master (GM) runs everyone else and the world.',
    related: [],
  },
  {
    slug: 'the-core-loop',
    title: 'The Core Loop',
    chapter: 'Foundations',
    tags: ['core'],
    body: 'Describe what you do, roll to see if it works, resolve the outcome, and let the fiction move on. The GM asks for a roll only when the result is uncertain and the outcome matters.',
    related: ['dice-and-rolls'],
  },
  {
    slug: 'the-golden-rule',
    title: 'The Golden Rule',
    chapter: 'Foundations',
    tags: ['core'],
    body: 'The GM is the final arbiter of the rules at the table. Fiction first: if a rule would contradict something the story has already established, the story wins.',
    related: [],
  },
  {
    slug: 'dice-and-rolls',
    title: 'Dice & Rolls',
    chapter: 'Foundations',
    tags: ['core', 'mechanics'],
    body: 'Roll a pool of d6s equal to the relevant attribute value plus any skill ranks that apply. Every die showing a 5 or a 6 counts as one success. Unless a special rule says otherwise, 1s are ordinary dice, not failures.',
    related: ['difficulties', 'critical-hits'],
  },
  {
    slug: 'difficulties',
    title: 'Difficulties',
    chapter: 'Foundations',
    tags: ['mechanics'],
    body: 'A difficulty is the number of successes a check needs: Easy 1, Standard 2, Hard 3, Dire 4. The GM sets difficulty from the situation, never from the dice already rolling.',
    related: ['skill-checks', 'degrees-of-success'],
  },
  {
    slug: 'advantage-and-disadvantage',
    title: 'Advantage & Disadvantage',
    chapter: 'Foundations',
    tags: ['mechanics'],
    body: 'Advantage adds one extra die to your pool. Disadvantage removes one die from your pool, to a minimum of one die. A die added by advantage that falls beyond your pool size still scores successes normally.',
    related: ['dice-and-rolls'],
  },
  {
    slug: 'degrees-of-success',
    title: 'Degrees of Success',
    chapter: 'Foundations',
    tags: ['mechanics'],
    body: 'Meet the difficulty and you succeed. Every two excess successes grant one degree. One degree is a clean success; two or more unlock a bonus effect chosen with the GM\'s nod.',
    related: ['difficulties'],
  },

  {
    slug: 'attributes',
    title: 'Attributes',
    chapter: 'Characters',
    tags: ['character'],
    body: 'Every hero has four attributes: Body (strength and grit), Agility (speed and dexterity), Mind (wits and learning), and Spirit (will and presence). Attribute values run 1 to 5 and set the base die count for related checks.',
    related: ['skills'],
  },
  {
    slug: 'skills',
    title: 'Skills',
    chapter: 'Characters',
    tags: ['character'],
    body: 'Skills turn an attribute into a specialty: Melee, Stealth, Lore, Persuasion, and more. Each rank adds one die when that skill applies. A hero can never hold more than three ranks in a single skill.',
    related: ['attributes', 'skill-checks'],
  },
  {
    slug: 'ancestries',
    title: 'Ancestries',
    chapter: 'Characters',
    tags: ['character'],
    body: 'Choose Human, Dwarf, Elf, or Goblin. Humans reroll one die per session. Dwarves have Dark Sight (see Light & Darkness). Elves sleep lightly and never need full slumber. Goblins gain advantage on checks to hide or flee.',
    related: ['light-and-darkness', 'advantage-and-disadvantage'],
  },
  {
    slug: 'classes',
    title: 'Classes',
    chapter: 'Characters',
    tags: ['character'],
    body: 'Choose Fighter, Rogue, Cleric, or Wizard. Fighters start with two weapon skills. Rogues start with Stealth and a knack for surprise. Clerics start with the Mend talent and Preparation. Wizards start with three spells known.',
    related: ['skills', 'leveling-and-talents'],
  },
  {
    slug: 'health-and-stamina',
    title: 'Health & Stamina',
    chapter: 'Characters',
    tags: ['character', 'combat'],
    body: 'A hero has Health equal to 6 plus Body, and Stamina equal to 6 plus Agility. Stamina powers stunts and special actions. When damage is not meant to kill, it depletes Stamina first and Health only when Stamina is empty.',
    related: ['armor-and-damage', 'wounds-and-dying'],
  },
  {
    slug: 'leveling-and-talents',
    title: 'Leveling & Talents',
    chapter: 'Characters',
    tags: ['character', 'progression'],
    body: 'You gain a level at each experience milestone. At every level you choose one new talent from your class list or the general list.',
    related: ['experience-and-milestones'],
  },
  {
    slug: 'gear-and-encumbrance',
    title: 'Gear & Encumbrance',
    chapter: 'Characters',
    tags: ['equipment'],
    body: 'A hero carries up to 10 plus Body items without penalty. Every item beyond that imposes disadvantage on Agility checks. Armour and weapons each count as one item.',
    related: ['action-economy'],
  },

  {
    slug: 'action-economy',
    title: 'Action Economy',
    chapter: 'Actions & Checks',
    tags: ['combat'],
    body: 'On your turn you get one action, one move, and one quick action. An action attacks, casts, or uses an item. A move covers up to 30 feet. A quick action draws a weapon, opens a door, or drops prone.',
    related: ['initiative', 'attacks'],
  },
  {
    slug: 'skill-checks',
    title: 'Skill Checks',
    chapter: 'Actions & Checks',
    tags: ['mechanics'],
    body: 'Use a skill: roll the attribute plus skill ranks against the difficulty the situation sets. State your approach before rolling; the GM uses it to pick the attribute and the skill.',
    related: ['difficulties', 'contested-checks'],
  },
  {
    slug: 'contested-checks',
    title: 'Contested Checks',
    chapter: 'Actions & Checks',
    tags: ['mechanics'],
    body: 'When two sides push against each other both roll. The side with more successes wins; ties go to the defender, or to whoever set the contest in motion.',
    related: ['skill-checks'],
  },
  {
    slug: 'rest-and-recovery',
    title: 'Rest & Recovery',
    chapter: 'Actions & Checks',
    tags: ['downtime'],
    body: 'A short rest is one hour of light activity away from combat and hard travel; it restores all Stamina. A long rest is a full night of safety and food in shelter; it restores all Health and clears most conditions.',
    related: ['downtime-activities', 'wounds-and-dying'],
  },

  {
    slug: 'initiative',
    title: 'Initiative',
    chapter: 'Combat',
    tags: ['combat'],
    body: 'At the start of combat each side rolls an Easy Agility check. Actions resolve best side first, then down the order. Ties with the GM act on the same count as the GM; order inside a side is up to the players.',
    related: ['action-economy'],
  },
  {
    slug: 'attacks',
    title: 'Attacks',
    chapter: 'Combat',
    tags: ['combat'],
    body: 'To attack, roll your relevant attribute plus weapon skill against a Standard difficulty of 2. A ranged attack uses Agility; a melee attack uses Body. Success lets you roll damage.',
    related: ['armor-and-damage', 'critical-hits', 'two-weapon-fighting'],
  },
  {
    slug: 'armor-and-damage',
    title: 'Armor & Damage',
    chapter: 'Combat',
    tags: ['combat'],
    body: 'A successful attack deals the weapon\'s base damage to Health plus one point per excess success. If the target wears armour, roll its dice and subtract the successes from the damage dealt.',
    related: ['health-and-stamina', 'attacks'],
  },
  {
    slug: 'critical-hits',
    title: 'Critical Hits',
    chapter: 'Combat',
    tags: ['combat'],
    body: 'When any die in the attack roll shows a 6, that die counts as two successes. If the total still meets the difficulty the attack hits, and the extra successes add damage as normal.',
    related: ['dice-and-rolls', 'attacks'],
  },
  {
    slug: 'cover-and-positioning',
    title: 'Cover & Positioning',
    chapter: 'Combat',
    tags: ['combat'],
    body: 'Partial cover — a wall edge, a crate, a tree — grants one extra die on checks to avoid ranged attacks. Total cover hides you entirely and makes you an untargetable enemy. Higher ground grants advantage on ranged attacks.',
    related: ['attacks', 'advantage-and-disadvantage'],
  },
  {
    slug: 'two-weapon-fighting',
    title: 'Two-Weapon Fighting',
    chapter: 'Combat',
    tags: ['combat'],
    body: 'A hero who fights with two light weapons may attack twice on their turn, once with each weapon. Both attacks are normal checks made with the same action.',
    related: ['attacks', 'action-economy', 'armor-and-damage'],
  },
  {
    slug: 'wounds-and-dying',
    title: 'Wounds & Dying',
    chapter: 'Combat',
    tags: ['combat'],
    body: 'When your Health drops to 0 you fall unconscious but stable; you do not bleed out on your own. You awaken with 1 Health after a short rest.',
    related: ['health-and-stamina', 'conditions', 'rest-and-recovery'],
  },
  {
    slug: 'conditions',
    title: 'Conditions',
    chapter: 'Combat',
    tags: ['combat'],
    body: 'Blinded: disadvantage to attack and to avoid. Prone: disadvantage to attack with melee; you are easier to hit from range. Restrained: cannot move, disadvantage to defend. Poisoned: disadvantage on all checks until cured. Grappled: cannot move; escape with a contested Agility check.',
    related: ['wounds-and-dying', 'rest-and-recovery'],
  },

  {
    slug: 'spells-and-schools',
    title: 'Spells & Schools',
    chapter: 'Magic',
    tags: ['magic'],
    body: 'Magic is divided into four schools: Flame, Frost, Mind, and Hallow. A caster knows a number of spells equal to their level plus one. Casting needs a free hand for gestures and a whispered chant.',
    related: ['casting-spells'],
  },
  {
    slug: 'casting-spells',
    title: 'Casting Spells',
    chapter: 'Magic',
    tags: ['magic'],
    body: 'To cast, roll Mind plus your spellcasting ranks against a Standard difficulty of 2. Each spell costs a spell slot of its level, chosen when you cast. A failed cast still spends the slot and nothing happens.',
    related: ['spells-and-schools', 'concentration'],
  },
  {
    slug: 'concentration',
    title: 'Concentration',
    chapter: 'Magic',
    tags: ['magic'],
    body: 'Spells that last beyond an instant require concentration. Moving more than half your move, taking damage, or casting another concentration spell ends the effect at the start of your next turn.',
    related: ['casting-spells'],
  },
  {
    slug: 'restoration-and-cures',
    title: 'Cure Wounds & Restoration',
    chapter: 'Magic',
    tags: ['magic', 'healing'],
    body: 'Hallow magic heals. Cure Wounds restores 3 Health and 3 Stamina, or brings a dying ally to 1 Health on a touch with no roll needed.',
    related: ['casting-spells', 'wounds-and-dying'],
  },

  {
    slug: 'movement-and-pace',
    title: 'Movement & Pace',
    chapter: 'Adventuring',
    tags: ['exploration'],
    body: 'A move action covers up to 30 feet. Hustling to 60 feet costs your action as well as your move. Difficult terrain costs double movement.',
    related: ['action-economy', 'exploration-and-travel'],
  },
  {
    slug: 'exploration-and-travel',
    title: 'Exploration & Travel',
    chapter: 'Adventuring',
    tags: ['exploration'],
    body: 'Travel is measured in watches of four hours. Each watch the GM rolls a hazard check: two successes is a peaceful watch, one is an encounter, none is an ambush or bad weather.',
    related: ['movement-and-pace'],
  },
  {
    slug: 'light-and-darkness',
    title: 'Light & Darkness',
    chapter: 'Adventuring',
    tags: ['exploration'],
    body: 'Torches and lanterns cast 30 feet of clear light. Dwarves have Dark Sight and see clearly through darkness up to 60 feet; everyone else in darkness is effectively blinded.',
    related: ['ancestries', 'exploration-and-travel'],
  },
  {
    slug: 'crafting-and-alchemy',
    title: 'Crafting & Alchemy',
    chapter: 'Adventuring',
    tags: ['downtime'],
    body: 'With a workshop and an hour of work you can craft an item of your level or lower. Alchemy needs Mind and the Alchemist skill; a failed crafting roll wastes the materials.',
    related: ['downtime-activities'],
  },
  {
    slug: 'downtime-activities',
    title: 'Downtime Activities',
    chapter: 'Adventuring',
    tags: ['downtime'],
    body: 'Between adventures a hero can train a skill (a week and a Standard check), scribe a spell scroll (half a day and the spell slot), or carouse to forge an ally and a rumour. A session covers a season of downtime.',
    related: ['rest-and-recovery', 'crafting-and-alchemy'],
  },
  {
    slug: 'experience-and-milestones',
    title: 'Experience & Milestones',
    chapter: 'Game Master',
    tags: ['progression', 'gm'],
    body: 'Heroes level on milestones, not body counts. Completing a quest, a daring feat, or a long-term goal earns the party a milestone, and each character present gains a level at the end of the session.',
    related: ['leveling-and-talents'],
  },
  {
    slug: 'glossary-and-keywords',
    title: 'Glossary & Keywords',
    chapter: 'Game Master',
    tags: ['reference'],
    body: 'Advantage: roll an extra die. Disadvantage: lose a die (minimum one). Check: attribute plus skill dice against a difficulty. Pool: the dice you roll. Slot: the resource spent to cast a spell. Watch: four hours of travel.',
    related: ['dice-and-rolls'],
  },
];

export const errataItems = [
  {
    slug: 'e-twoweapon-override',
    title: '[OVERRIDE] Two-Weapon Fighting rebalanced',
    ruleRef: 'two-weapon-fighting',
    changeType: 'override',
    text: 'OVERRIDE: Wielding two light weapons no longer grants a second attack. Instead it grants advantage on a single attack, and requires the Ambidextrous talent to attempt at all. The rulebook\'s second attack is replaced by this ruling.',
    sourceUrl: 'https://rules.steeldusk.example/errata/#two-weapon-fighting',
    effectiveDate: '2025-03-01',
  },
  {
    slug: 'e-wounds-deathsaves',
    title: '[OVERRIDE] Death saves replace auto-stability',
    ruleRef: 'wounds-and-dying',
    changeType: 'override',
    text: 'OVERRIDE: A hero at 0 Health is Dying, not stable. Each round at 0 Health, roll a Body check at Hard difficulty (3). Three failed checks before any success is death. A success stabilizes you at 0 Health, conscious but unable to act until helped.',
    sourceUrl: 'https://rules.steeldusk.example/errata/#death-saves',
    effectiveDate: '2025-08-15',
  },
  {
    slug: 'e-darksight',
    title: '[OVERRIDE] Dark Sight range halved',
    ruleRef: 'light-and-darkness',
    changeType: 'override',
    text: 'OVERRIDE: Dwarven Dark Sight now reaches only 30 feet. Past 30 feet, treat darkness as dim gloom and roll all checks with disadvantage. The 60-foot Dark Sight described in Light & Darkness is replaced.',
    sourceUrl: 'https://rules.steeldusk.example/errata/#dark-sight',
    effectiveDate: '2026-01-10',
  },
  {
    slug: 'e-talent-cadence',
    title: '[OVERRIDE] Talent cadence changed',
    ruleRef: 'leveling-and-talents',
    changeType: 'override',
    text: 'OVERRIDE: Talents are now gained every second level instead of every level. At level 1 a hero instead chooses a Signature Talent. Leveling & Talents is amended accordingly.',
    sourceUrl: 'https://rules.steeldusk.example/errata/#talent-cadence',
    effectiveDate: '2026-05-20',
  },
  {
    slug: 'e-advantage-stack',
    title: '[CLARIFY] Advantage does not stack',
    ruleRef: 'advantage-and-disadvantage',
    changeType: 'clarify',
    text: 'CLARIFICATION: Advantage from multiple sources still adds only one die; it never escalates to two. Disadvantage likewise applies only once, to a minimum of one die. This confirms Advantage & Disadvantage.',
    sourceUrl: 'https://rules.steeldusk.example/errata/#advantage-stacking',
    effectiveDate: '2026-02-11',
  },
  {
    slug: 'e-nat6',
    title: '[CLARIFY] A natural 6 is not an automatic hit',
    ruleRef: 'critical-hits',
    changeType: 'clarify',
    text: 'CLARIFICATION: A die showing 6 counts as two successes but does not by itself guarantee a hit. The attack roll must still meet its difficulty before damage is rolled. See Critical Hits.',
    sourceUrl: 'https://rules.steeldusk.example/errata/#natural-6',
    effectiveDate: '2025-09-30',
  },
  {
    slug: 'e-shortrest',
    title: '[CLARIFY] Short rest needs a quiet hour',
    ruleRef: 'rest-and-recovery',
    changeType: 'clarify',
    text: 'CLARIFICATION: A short rest requires one quiet hour free of combat, hazards, and hard travel. Taking damage resets the rest timer.',
    sourceUrl: 'https://rules.steeldusk.example/errata/#short-rest',
    effectiveDate: '2025-12-01',
  },
  {
    slug: 'e-milestone-once',
    title: '[CLARIFY] Milestones are awarded once',
    ruleRef: 'experience-and-milestones',
    changeType: 'clarify',
    text: 'CLARIFICATION: A milestone is awarded once, to the party, and levels every character present at that session. Players who join a later session do not gain the milestone retroactively.',
    sourceUrl: 'https://rules.steeldusk.example/errata/#milestones',
    effectiveDate: '2026-03-18',
  },
  {
    slug: 'e-upcast',
    title: '[CLARIFY] Upcasting costs a higher slot',
    ruleRef: 'casting-spells',
    changeType: 'clarify',
    text: 'CLARIFICATION: You may cast a lower-level spell by spending a higher-level slot. This extends the spell\'s duration or range but never adds dice to the casting roll.',
    sourceUrl: 'https://rules.steeldusk.example/errata/#upcasting',
    effectiveDate: '2025-11-22',
  },
  {
    slug: 'e-armor-order',
    title: '[CLARIFY] Armour reduces damage after the roll',
    ruleRef: 'armor-and-damage',
    changeType: 'clarify',
    text: 'CLARIFICATION: Roll armour dice after damage is rolled, subtract the armour successes from the incoming damage, and never drop below 1 point of damage taken. This makes the order implied by Armor & Damage explicit.',
    sourceUrl: 'https://rules.steeldusk.example/errata/#armour-order',
    effectiveDate: '2026-07-05',
  },
];

export const faqItems = [
  {
    slug: 'f-twoweapons',
    question: 'Can I attack twice if I wield two short swords?',
    answer:
      'Not by default. The current ruling ([OVERRIDE] Two-Weapon Fighting rebalanced, effective 2025-03-01) replaces the rulebook\'s second attack: two light weapons now grant advantage on a single attack, and you must have the Ambidextrous talent.',
    ruleRef: ['two-weapon-fighting'],
    sourceUrl: 'https://rules.steeldusk.example/faq/#two-weapons',
  },
  {
    slug: 'f-health-0',
    question: 'What happens when my Health hits 0?',
    answer:
      'You are Dying. The rulebook said you would be stable and unconscious; the current errata overrides that: each round at 0 Health you roll a Hard Body check, and three failures before any success kill you. A success stabilizes you at 0 Health.',
    ruleRef: ['wounds-and-dying'],
    sourceUrl: 'https://rules.steeldusk.example/faq/#health-zero',
  },
  {
    slug: 'f-advantage-stack',
    question: 'Does advantage from high ground stack with advantage from a spell?',
    answer:
      'No. Per the clarification on Advantage & Disadvantage, advantage applies only once; extra sources add nothing beyond the single bonus die.',
    ruleRef: ['advantage-and-disadvantage'],
    sourceUrl: 'https://rules.steeldusk.example/faq/#advantage-stacking',
  },
  {
    slug: 'f-short-rest',
    question: 'When can I take a short rest?',
    answer:
      'A short rest is one quiet hour: no combat, no hazards, and no hard travel. Taking damage resets the timer. It restores all Stamina, and you awaken stable at 1 Health if you were at 0.',
    ruleRef: ['rest-and-recovery'],
    sourceUrl: 'https://rules.steeldusk.example/faq/#short-rest',
  },
  {
    slug: 'f-nat-6',
    question: 'Is a natural 6 always a hit?',
    answer:
      'No. A 6 counts as two successes, but the attack roll as a whole must still meet the Standard difficulty before damage is rolled.',
    ruleRef: ['critical-hits'],
    sourceUrl: 'https://rules.steeldusk.example/faq/#natural-6',
  },
  {
    slug: 'f-cleric-heal',
    question: 'Can a Cleric save a dying ally?',
    answer:
      'Yes. Hallow magic restores Health and Stamina, and Cure Wounds can bring a dying ally to 1 Health on a touch with no roll. Until that moment, the death-save ruling in Wounds & Dying still applies.',
    ruleRef: ['restoration-and-cures', 'wounds-and-dying'],
    sourceUrl: 'https://rules.steeldusk.example/faq/#cleric-heal',
  },
  {
    slug: 'f-actions',
    question: 'How many actions do I get on my turn?',
    answer:
      'One action, one move, and one quick action. An attack or casting a spell counts as your action.',
    ruleRef: ['action-economy'],
    sourceUrl: 'https://rules.steeldusk.example/faq/#actions',
  },
  {
    slug: 'f-cover',
    question: 'Does hiding behind a wall fully block arrows?',
    answer:
      'Total cover blocks you from being targeted at all. Partial cover, like a crate or an arrow slit, adds one die to your checks to avoid ranged attacks.',
    ruleRef: ['cover-and-positioning'],
    sourceUrl: 'https://rules.steeldusk.example/faq/#cover',
  },
  {
    slug: 'f-upcast',
    question: 'Can I use a high-level slot to cast a low-level spell?',
    answer:
      'Yes. Upcasting with a higher slot extends duration or range but never adds dice to the casting roll, per the clarification on Casting Spells.',
    ruleRef: ['casting-spells'],
    sourceUrl: 'https://rules.steeldusk.example/faq/#upcast',
  },
  {
    slug: 'f-talent',
    question: 'How do I gain a new talent?',
    answer:
      'Every second level, per the current errata, you choose a new talent. At level 1 you instead choose a Signature Talent. The older rulebook text granting a talent every level is overridden.',
    ruleRef: ['leveling-and-talents'],
    sourceUrl: 'https://rules.steeldusk.example/faq/#talent',
  },
];